id: P000328
initial_creation_type: ocr
created_at: 12/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN2397
  title: དཔལ་ཆེན་ཧའོ་དགོན་གྱི་གནས་ཡིག
  author: ''
  volumes:
    de20300642b040aab388bca0bfe3ca2d:
      image_group_id: I3CN2399
      title: Volume 1 of dpal chen ha'o dgon gyi gnas yig
      volume_number: 1
      total_pages: 74
      base_file: v001.txt
